### ISSUE TITLE
Cleanup: Use Promises instead of callbacks

### ISSUE THREAD

**Issue by meyskens** [Innovate-Technologies/ITFrame#2]
From @leoetlino 

Currently, our code is a mix of callbacks, `wait.for` and modern ES6 stuff… Which isn't an ideal situation. We should start cleaning up the code and use promises instead of callbacks and `wait.for`. This would allow us to write code that is easier to read, understand and shorter/more concise. Not to mention that we can then use ES7 `async`/`await` to get even more readable and concise code.

This will be an ongoing task: **any new code should use promises** instead of callbacks. As for old code, there will be code refactors to modernise the whole codebase.

**Comment by leoetlino** [comment]
Not really something that can be easily tracked in an issue, I guess… so I'm going to close this. Let's just keep this in mind for any new code.
