### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by osnapitzjamie** [innovate-technologies/itframe#40]
the config file is not included?

**Comment by meyskens** [comment]
There is an actual reason for that. ITFrame is super interlinked with our legacy closed source backend, even if I gave you the config file it would be useless. We have made some changes in the latest updates to make use of middleware classes to be able to interchange those in the future. 

We've also been planning to release a branch called ITFrame CE with all our legacy stuff removed but we never did see the time for it nor do in the near future. All help is welcome there.

**Comment by osnapitzjamie** [comment]
All I wanna do is use the autodj but it requires ITFrame :(

**Comment by meyskens** [comment]
It also lacks an open source audio engine for now so not fully usable.

**Comment by osnapitzjamie** [comment]
so i gotta use sam broadcaster on a dedi? D:

**Comment by meyskens** [comment]
there are more options, but I don't think a bug tracker is the right place to discuss that
